---
abstract: 'Bump and reversion $VERSION on release'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.026
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 4.300036, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-ReversionOnRelease
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Dist::Zilla: 4.2
  Version::Next: 0.002
  perl: 5.008005
resources:
  bugtracker: https://github.com/miyagawa/Dist-Zilla-Plugin-ReversionOnRelease/issues
  homepage: https://github.com/miyagawa/Dist-Zilla-Plugin-ReversionOnRelease
  repository: https://github.com/miyagawa/Dist-Zilla-Plugin-ReversionOnRelease.git
version: 0.05
